name: Deploy to EKS

on:
  push:
    branches:
      - featureB

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.USERNAME }}
          aws-secret-access-key: ${{ secrets.PASSWORD }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: |
          docker build -t my-app .
          docker tag my-app:latest ${{ steps.ecr.outputs.registry }}/my-app:latest

      - name: Push Docker Image
        run: |
          docker push ${{ steps.ecr.outputs.registry }}/my-app:latest

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml