name: OIDC Example

on:
  push:
    branches:
      - featureB

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required to checkout repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::599548906743:oidc-provider/token.actions.githubusercontent.com
          aws-region: us-east-1

      - name: Verify identity
        run: aws sts get-caller-identity