name : Deploy Argocd Application

on: 
    workflow_dispatch:
        inputs:
            cluster_name:
                description: 'EKS CLuster name'
                required: false
                default: ''
    repository_dispatch:
        types: [deploy_argocd_app]


jobs:
    dpeloy-argocd-applications:
        runs-on: ubuntu-latest
        steps:
            - name: checkout Repository
              uses: actions/checkout@v2
            
            - name: Install Kubectl
              uses: azure/setup-kubectl@v1

            - name: set up AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with :
                aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
                aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                aws-region: eu-east-1

            - name: Update kubeconfig
              run: |
                EKS_CLUSTER_NAME= "${{github.envent.inputs.cluster_name || github.event.client_payload.cluster_name}}"
                if [-z "$EKS_CLUSTER_NAME"]; then
                   echo "EKS Cluster Name is required."
                   exit 1
                fi
                aws eks update-kubeconfig --name "$EKS_CLUSTER_NAME" --region eu-west-1
            
            - name : apply argocd Application manifest
              run: kubectl apply -f ./argocd_manifest.yaml




